### ISSUE TITLE
Fresh Install of cakephp 2.6.1 and this plugin doesn't work

### ISSUE THREAD

**Issue by skiv3r** [CakeDC/i18n#31]
Hello,

I am testing out this plugin in a fresh cake install, 1 line of text in /View/Pages/home.ctp, cake i18n extract and then poedit to translate that line, saved in /app/Locale/[locale]/LC_MESSAGES/default.po

Followed every line on the quick start documentation. What did I overlook ?

Regards,

**Comment by omnuvito** [comment]
Hi @skiv3r, Can you check if your issue is the same shown in this other? ([#32](https://github.com/CakeDC/i18n/issues/32))

**Comment by Megslalk** [comment]
This issue will be closed; Please feel free to re-open or create a new issue if you still need assistance. Thanks!
