### ISSUE TITLE
Implementation in CakePHP 3

### ISSUE THREAD

**Issue by borhademohini** [CakeDC/i18n#39]
Hello Team,

How can I integrate i18n class in cakePHP 3.

I am following the steps given in the document but it is throwing an error saying, "Class 'App' not found".

And if I include this line use Cake\Core\App; in the code to remove the above error, it comes out with another error i.e "Cannot find route class I18nRoute".

Kindly help me to get this plugin implemented in cakePHP. 

Thanks.

**Comment by andre-pdassis** [comment]
@borhademohini Currently there is no available version for CakePHP 3. This plugin is for use with CakePHP 2. I will see with the others the chances of a new release.

**Comment by Megslalk** [comment]
Closing issue - Please re-open if necessary!
